# action.yml
name: 'Coding Standard for Magento 2'
description: 'Github Action for magento 2'
outputs:
  time: # id of output
    description: 'The test result'
runs:
  using: 'docker'
  image: 'Dockerfile'
